### ISSUE TITLE
Configurar ambiente

### ISSUE THREAD

**Issue by CamilaFerrer** [MDS-Caliandra/TBL#2]
Sistema operacional: https://victorarnaud.github.io/TBL/contribuicao/install/
ZenHub: https://www.zenhub.com/

**Tarefas:**
Cada integrante deve comentar na Issue um checklist sobre o andamento da configuração do ambiente.

**Comment by CamilaFerrer** [comment]
ZenHub instalado no meu navegador

**Comment by GabrielOak** [comment]
ZenHub instalado e ambiente configurado.

**Comment by MatheusFilipe95** [comment]
ZenHub instalado no meu navegador e ambiente configurado.

**Comment by ritzare** [comment]
Configuração do ambiente concluída.

**Comment by Alexandree-Santos** [comment]
ZenHub instalado no meu navegador

**Comment by Nief13** [comment]
ZenHub instalado no meu navegador, configuração do ambiente em andamento

**Comment by CamilaFerrer** [comment]
Configuração de ambiente concluída

**Comment by Nief13** [comment]
Configuração de ambiente concluída
