### ISSUE TITLE
Quadro de Conhecimento

### ISSUE THREAD

**Issue by CamilaFerrer** [MDS-Caliandra/TBL#3]
**Tarefa:**
* Criar quadro de conhecimento

**OBS:** Cada integrante deve preencher seu nível de conhecimento no quadro e comentar na issue quando tiver preenchido.

**Comment by CamilaFerrer** [comment]
Meu quadro de conhecimento foi preenchido

**Comment by ritzare** [comment]
Quadro de conhecimento preenchido.

**Comment by Alexandree-Santos** [comment]
Meu quadro de conhecimento foi preenchido

**Comment by Nief13** [comment]
Meu quadro de conhecimento foi preenchido

**Comment by MatheusFilipe95** [comment]
Meu quadro de conhecimento foi preenchido.
