### ISSUE TITLE
Documentação para levantar requisitos

### ISSUE THREAD

**Issue by CamilaFerrer** [MDS-Caliandra/TBL#6]
**Tarefas:**
* Criar documento que será utilizado para levantamento de requisitos.

**OBS:** Todos os integrantes deverão criar perguntas para colocar no documento e comentar na issue quando as tiver inserido.

**Comment by Nief13** [comment]
Documento criado no Drive

**Comment by CamilaFerrer** [comment]
Inseri algumas perguntas no documento

**Comment by ritzare** [comment]
Criei perguntas no documento.

**Comment by MatheusFilipe95** [comment]
Inseri algumas perguntas no documento.

**Comment by GabrielOak** [comment]
Adicionei novas perguntas ao documento.
